#ifndef __TUPLE_SPACE_HELPERS__
#define __TUPLE_SPACE_HELPERS__

#define CONCATENATE(arg1, arg2)   CONCATENATE1(arg1, arg2)
#define CONCATENATE1(arg1, arg2)  CONCATENATE2(arg1, arg2)
#define CONCATENATE2(arg1, arg2)  arg1##arg2

#define FOR_EACH_1(what, arg, x, ...) what(x, 0, arg)
#define FOR_EACH_2(what, arg, x, ...) what(x, 1, arg) FOR_EACH_1(what, arg, ## __VA_ARGS__)
#define FOR_EACH_3(what, arg, x, ...) what(x, 2, arg) FOR_EACH_2(what, arg, ## __VA_ARGS__)
#define FOR_EACH_4(what, arg, x, ...) what(x, 3, arg) FOR_EACH_3(what, arg, ## __VA_ARGS__)
#define FOR_EACH_5(what, arg, x, ...) what(x, 4, arg) FOR_EACH_4(what, arg, ## __VA_ARGS__)
#define FOR_EACH_6(what, arg, x, ...) what(x, 5, arg) FOR_EACH_5(what, arg, ## __VA_ARGS__)
#define FOR_EACH_7(what, arg, x, ...) what(x, 6, arg) FOR_EACH_6(what, arg, ## __VA_ARGS__)
#define FOR_EACH_8(what, arg, x, ...) what(x, 7, arg) FOR_EACH_7(what, arg, ## __VA_ARGS__)
#define FOR_EACH_9(what, arg, x, ...) what(x, 8, arg) FOR_EACH_8(what, arg, ## __VA_ARGS__)
#define FOR_EACH_10(what, arg, x, ...) what(x, 9, arg) FOR_EACH_9(what, arg, ## __VA_ARGS__)
#define FOR_EACH_11(what, arg, x, ...) what(x, 10, arg) FOR_EACH_10(what, arg, ## __VA_ARGS__)
#define FOR_EACH_12(what, arg, x, ...) what(x, 11, arg) FOR_EACH_11(what, arg, ## __VA_ARGS__)
#define FOR_EACH_13(what, arg, x, ...) what(x, 12, arg) FOR_EACH_12(what, arg, ## __VA_ARGS__)
#define FOR_EACH_14(what, arg, x, ...) what(x, 13, arg) FOR_EACH_13(what, arg, ## __VA_ARGS__)
#define FOR_EACH_15(what, arg, x, ...) what(x, 14, arg) FOR_EACH_14(what, arg, ## __VA_ARGS__)
#define FOR_EACH_16(what, arg, x, ...) what(x, 15, arg) FOR_EACH_15(what, arg, ## __VA_ARGS__)
#define FOR_EACH_17(what, arg, x, ...) what(x, 16, arg) FOR_EACH_16(what, arg, ## __VA_ARGS__)
#define FOR_EACH_18(what, arg, x, ...) what(x, 17, arg) FOR_EACH_17(what, arg, ## __VA_ARGS__)
#define FOR_EACH_19(what, arg, x, ...) what(x, 18, arg) FOR_EACH_18(what, arg, ## __VA_ARGS__)
#define FOR_EACH_20(what, arg, x, ...) what(x, 19, arg) FOR_EACH_19(what, arg, ## __VA_ARGS__)
#define FOR_EACH_21(what, arg, x, ...) what(x, 20, arg) FOR_EACH_20(what, arg, ## __VA_ARGS__)
#define FOR_EACH_22(what, arg, x, ...) what(x, 21, arg) FOR_EACH_21(what, arg, ## __VA_ARGS__)
#define FOR_EACH_23(what, arg, x, ...) what(x, 22, arg) FOR_EACH_22(what, arg, ## __VA_ARGS__)
#define FOR_EACH_24(what, arg, x, ...) what(x, 23, arg) FOR_EACH_23(what, arg, ## __VA_ARGS__)
#define FOR_EACH_25(what, arg, x, ...) what(x, 24, arg) FOR_EACH_24(what, arg, ## __VA_ARGS__)
#define FOR_EACH_26(what, arg, x, ...) what(x, 25, arg) FOR_EACH_25(what, arg, ## __VA_ARGS__)
#define FOR_EACH_27(what, arg, x, ...) what(x, 26, arg) FOR_EACH_26(what, arg, ## __VA_ARGS__)
#define FOR_EACH_28(what, arg, x, ...) what(x, 27, arg) FOR_EACH_27(what, arg, ## __VA_ARGS__)
#define FOR_EACH_29(what, arg, x, ...) what(x, 28, arg) FOR_EACH_28(what, arg, ## __VA_ARGS__)
#define FOR_EACH_30(what, arg, x, ...) what(x, 29, arg) FOR_EACH_29(what, arg, ## __VA_ARGS__)
#define FOR_EACH_31(what, arg, x, ...) what(x, 30, arg) FOR_EACH_30(what, arg, ## __VA_ARGS__)
#define FOR_EACH_32(what, arg, x, ...) what(x, 31, arg) FOR_EACH_31(what, arg, ## __VA_ARGS__)
#define FOR_EACH_33(what, arg, x, ...) what(x, 32, arg) FOR_EACH_32(what, arg, ## __VA_ARGS__)
#define FOR_EACH_34(what, arg, x, ...) what(x, 33, arg) FOR_EACH_33(what, arg, ## __VA_ARGS__)
#define FOR_EACH_35(what, arg, x, ...) what(x, 34, arg) FOR_EACH_34(what, arg, ## __VA_ARGS__)
#define FOR_EACH_36(what, arg, x, ...) what(x, 35, arg) FOR_EACH_35(what, arg, ## __VA_ARGS__)
#define FOR_EACH_37(what, arg, x, ...) what(x, 36, arg) FOR_EACH_36(what, arg, ## __VA_ARGS__)
#define FOR_EACH_38(what, arg, x, ...) what(x, 37, arg) FOR_EACH_37(what, arg, ## __VA_ARGS__)
#define FOR_EACH_39(what, arg, x, ...) what(x, 38, arg) FOR_EACH_38(what, arg, ## __VA_ARGS__)
#define FOR_EACH_40(what, arg, x, ...) what(x, 39, arg) FOR_EACH_39(what, arg, ## __VA_ARGS__)
#define FOR_EACH_41(what, arg, x, ...) what(x, 40, arg) FOR_EACH_40(what, arg, ## __VA_ARGS__)
#define FOR_EACH_42(what, arg, x, ...) what(x, 41, arg) FOR_EACH_41(what, arg, ## __VA_ARGS__)
#define FOR_EACH_43(what, arg, x, ...) what(x, 42, arg) FOR_EACH_42(what, arg, ## __VA_ARGS__)
#define FOR_EACH_44(what, arg, x, ...) what(x, 43, arg) FOR_EACH_43(what, arg, ## __VA_ARGS__)
#define FOR_EACH_45(what, arg, x, ...) what(x, 44, arg) FOR_EACH_44(what, arg, ## __VA_ARGS__)
#define FOR_EACH_46(what, arg, x, ...) what(x, 45, arg) FOR_EACH_45(what, arg, ## __VA_ARGS__)
#define FOR_EACH_47(what, arg, x, ...) what(x, 46, arg) FOR_EACH_46(what, arg, ## __VA_ARGS__)
#define FOR_EACH_48(what, arg, x, ...) what(x, 47, arg) FOR_EACH_47(what, arg, ## __VA_ARGS__)
#define FOR_EACH_49(what, arg, x, ...) what(x, 48, arg) FOR_EACH_48(what, arg, ## __VA_ARGS__)
#define FOR_EACH_50(what, arg, x, ...) what(x, 49, arg) FOR_EACH_49(what, arg, ## __VA_ARGS__)
#define FOR_EACH_51(what, arg, x, ...) what(x, 50, arg) FOR_EACH_50(what, arg, ## __VA_ARGS__)
#define FOR_EACH_52(what, arg, x, ...) what(x, 51, arg) FOR_EACH_51(what, arg, ## __VA_ARGS__)
#define FOR_EACH_53(what, arg, x, ...) what(x, 52, arg) FOR_EACH_52(what, arg, ## __VA_ARGS__)
#define FOR_EACH_54(what, arg, x, ...) what(x, 53, arg) FOR_EACH_53(what, arg, ## __VA_ARGS__)
#define FOR_EACH_55(what, arg, x, ...) what(x, 54, arg) FOR_EACH_54(what, arg, ## __VA_ARGS__)
#define FOR_EACH_56(what, arg, x, ...) what(x, 55, arg) FOR_EACH_55(what, arg, ## __VA_ARGS__)
#define FOR_EACH_57(what, arg, x, ...) what(x, 56, arg) FOR_EACH_56(what, arg, ## __VA_ARGS__)
#define FOR_EACH_58(what, arg, x, ...) what(x, 57, arg) FOR_EACH_57(what, arg, ## __VA_ARGS__)
#define FOR_EACH_59(what, arg, x, ...) what(x, 58, arg) FOR_EACH_58(what, arg, ## __VA_ARGS__)
#define FOR_EACH_60(what, arg, x, ...) what(x, 59, arg) FOR_EACH_59(what, arg, ## __VA_ARGS__)
#define FOR_EACH_61(what, arg, x, ...) what(x, 60, arg) FOR_EACH_60(what, arg, ## __VA_ARGS__)
#define FOR_EACH_62(what, arg, x, ...) what(x, 61, arg) FOR_EACH_61(what, arg, ## __VA_ARGS__)
#define FOR_EACH_63(what, arg, x, ...) what(x, 62, arg) FOR_EACH_62(what, arg, ## __VA_ARGS__)
#define FOR_EACH_64(what, arg, x, ...) what(x, 63, arg) FOR_EACH_63(what, arg, ## __VA_ARGS__)
#define FOR_EACH_65(what, arg, x, ...) what(x, 64, arg) FOR_EACH_64(what, arg, ## __VA_ARGS__)
#define FOR_EACH_66(what, arg, x, ...) what(x, 65, arg) FOR_EACH_65(what, arg, ## __VA_ARGS__)
#define FOR_EACH_67(what, arg, x, ...) what(x, 66, arg) FOR_EACH_66(what, arg, ## __VA_ARGS__)
#define FOR_EACH_68(what, arg, x, ...) what(x, 67, arg) FOR_EACH_67(what, arg, ## __VA_ARGS__)
#define FOR_EACH_69(what, arg, x, ...) what(x, 68, arg) FOR_EACH_68(what, arg, ## __VA_ARGS__)
#define FOR_EACH_70(what, arg, x, ...) what(x, 69, arg) FOR_EACH_69(what, arg, ## __VA_ARGS__)
#define FOR_EACH_71(what, arg, x, ...) what(x, 70, arg) FOR_EACH_70(what, arg, ## __VA_ARGS__)
#define FOR_EACH_72(what, arg, x, ...) what(x, 71, arg) FOR_EACH_71(what, arg, ## __VA_ARGS__)
#define FOR_EACH_73(what, arg, x, ...) what(x, 72, arg) FOR_EACH_72(what, arg, ## __VA_ARGS__)
#define FOR_EACH_74(what, arg, x, ...) what(x, 73, arg) FOR_EACH_73(what, arg, ## __VA_ARGS__)
#define FOR_EACH_75(what, arg, x, ...) what(x, 74, arg) FOR_EACH_74(what, arg, ## __VA_ARGS__)
#define FOR_EACH_76(what, arg, x, ...) what(x, 75, arg) FOR_EACH_75(what, arg, ## __VA_ARGS__)
#define FOR_EACH_77(what, arg, x, ...) what(x, 76, arg) FOR_EACH_76(what, arg, ## __VA_ARGS__)
#define FOR_EACH_78(what, arg, x, ...) what(x, 77, arg) FOR_EACH_77(what, arg, ## __VA_ARGS__)
#define FOR_EACH_79(what, arg, x, ...) what(x, 78, arg) FOR_EACH_78(what, arg, ## __VA_ARGS__)
#define FOR_EACH_80(what, arg, x, ...) what(x, 79, arg) FOR_EACH_79(what, arg, ## __VA_ARGS__)
#define FOR_EACH_81(what, arg, x, ...) what(x, 80, arg) FOR_EACH_80(what, arg, ## __VA_ARGS__)
#define FOR_EACH_82(what, arg, x, ...) what(x, 81, arg) FOR_EACH_81(what, arg, ## __VA_ARGS__)
#define FOR_EACH_83(what, arg, x, ...) what(x, 82, arg) FOR_EACH_82(what, arg, ## __VA_ARGS__)
#define FOR_EACH_84(what, arg, x, ...) what(x, 83, arg) FOR_EACH_83(what, arg, ## __VA_ARGS__)
#define FOR_EACH_85(what, arg, x, ...) what(x, 84, arg) FOR_EACH_84(what, arg, ## __VA_ARGS__)
#define FOR_EACH_86(what, arg, x, ...) what(x, 85, arg) FOR_EACH_85(what, arg, ## __VA_ARGS__)
#define FOR_EACH_87(what, arg, x, ...) what(x, 86, arg) FOR_EACH_86(what, arg, ## __VA_ARGS__)
#define FOR_EACH_88(what, arg, x, ...) what(x, 87, arg) FOR_EACH_87(what, arg, ## __VA_ARGS__)
#define FOR_EACH_89(what, arg, x, ...) what(x, 88, arg) FOR_EACH_88(what, arg, ## __VA_ARGS__)
#define FOR_EACH_90(what, arg, x, ...) what(x, 89, arg) FOR_EACH_89(what, arg, ## __VA_ARGS__)
#define FOR_EACH_91(what, arg, x, ...) what(x, 90, arg) FOR_EACH_90(what, arg, ## __VA_ARGS__)
#define FOR_EACH_92(what, arg, x, ...) what(x, 91, arg) FOR_EACH_91(what, arg, ## __VA_ARGS__)
#define FOR_EACH_93(what, arg, x, ...) what(x, 92, arg) FOR_EACH_92(what, arg, ## __VA_ARGS__)
#define FOR_EACH_94(what, arg, x, ...) what(x, 93, arg) FOR_EACH_93(what, arg, ## __VA_ARGS__)
#define FOR_EACH_95(what, arg, x, ...) what(x, 94, arg) FOR_EACH_94(what, arg, ## __VA_ARGS__)
#define FOR_EACH_96(what, arg, x, ...) what(x, 95, arg) FOR_EACH_95(what, arg, ## __VA_ARGS__)
#define FOR_EACH_97(what, arg, x, ...) what(x, 96, arg) FOR_EACH_96(what, arg, ## __VA_ARGS__)
#define FOR_EACH_98(what, arg, x, ...) what(x, 97, arg) FOR_EACH_97(what, arg, ## __VA_ARGS__)
#define FOR_EACH_99(what, arg, x, ...) what(x, 98, arg) FOR_EACH_98(what, arg, ## __VA_ARGS__)
#define FOR_EACH_100(what, arg, x, ...) what(x, 99, arg) FOR_EACH_99(what, arg, ## __VA_ARGS__)

#define FOR_EACH_UNDER_RECURSION_1(what, arg, x, ...) what(x, 0, arg)
#define FOR_EACH_UNDER_RECURSION_2(what, arg, x, ...) what(x, 1, arg) FOR_EACH_UNDER_RECURSION_1(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_3(what, arg, x, ...) what(x, 2, arg) FOR_EACH_UNDER_RECURSION_2(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_4(what, arg, x, ...) what(x, 3, arg) FOR_EACH_UNDER_RECURSION_3(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_5(what, arg, x, ...) what(x, 4, arg) FOR_EACH_UNDER_RECURSION_4(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_6(what, arg, x, ...) what(x, 5, arg) FOR_EACH_UNDER_RECURSION_5(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_7(what, arg, x, ...) what(x, 6, arg) FOR_EACH_UNDER_RECURSION_6(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_8(what, arg, x, ...) what(x, 7, arg) FOR_EACH_UNDER_RECURSION_7(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_9(what, arg, x, ...) what(x, 8, arg) FOR_EACH_UNDER_RECURSION_8(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_10(what, arg, x, ...) what(x, 9, arg) FOR_EACH_UNDER_RECURSION_9(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_11(what, arg, x, ...) what(x, 10, arg) FOR_EACH_UNDER_RECURSION_10(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_12(what, arg, x, ...) what(x, 11, arg) FOR_EACH_UNDER_RECURSION_11(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_13(what, arg, x, ...) what(x, 12, arg) FOR_EACH_UNDER_RECURSION_12(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_14(what, arg, x, ...) what(x, 13, arg) FOR_EACH_UNDER_RECURSION_13(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_15(what, arg, x, ...) what(x, 14, arg) FOR_EACH_UNDER_RECURSION_14(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_16(what, arg, x, ...) what(x, 15, arg) FOR_EACH_UNDER_RECURSION_15(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_17(what, arg, x, ...) what(x, 16, arg) FOR_EACH_UNDER_RECURSION_16(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_18(what, arg, x, ...) what(x, 17, arg) FOR_EACH_UNDER_RECURSION_17(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_19(what, arg, x, ...) what(x, 18, arg) FOR_EACH_UNDER_RECURSION_18(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_20(what, arg, x, ...) what(x, 19, arg) FOR_EACH_UNDER_RECURSION_19(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_21(what, arg, x, ...) what(x, 20, arg) FOR_EACH_UNDER_RECURSION_20(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_22(what, arg, x, ...) what(x, 21, arg) FOR_EACH_UNDER_RECURSION_21(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_23(what, arg, x, ...) what(x, 22, arg) FOR_EACH_UNDER_RECURSION_22(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_24(what, arg, x, ...) what(x, 23, arg) FOR_EACH_UNDER_RECURSION_23(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_25(what, arg, x, ...) what(x, 24, arg) FOR_EACH_UNDER_RECURSION_24(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_26(what, arg, x, ...) what(x, 25, arg) FOR_EACH_UNDER_RECURSION_25(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_27(what, arg, x, ...) what(x, 26, arg) FOR_EACH_UNDER_RECURSION_26(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_28(what, arg, x, ...) what(x, 27, arg) FOR_EACH_UNDER_RECURSION_27(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_29(what, arg, x, ...) what(x, 28, arg) FOR_EACH_UNDER_RECURSION_28(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_30(what, arg, x, ...) what(x, 29, arg) FOR_EACH_UNDER_RECURSION_29(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_31(what, arg, x, ...) what(x, 30, arg) FOR_EACH_UNDER_RECURSION_30(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_32(what, arg, x, ...) what(x, 31, arg) FOR_EACH_UNDER_RECURSION_31(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_33(what, arg, x, ...) what(x, 32, arg) FOR_EACH_UNDER_RECURSION_32(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_34(what, arg, x, ...) what(x, 33, arg) FOR_EACH_UNDER_RECURSION_33(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_35(what, arg, x, ...) what(x, 34, arg) FOR_EACH_UNDER_RECURSION_34(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_36(what, arg, x, ...) what(x, 35, arg) FOR_EACH_UNDER_RECURSION_35(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_37(what, arg, x, ...) what(x, 36, arg) FOR_EACH_UNDER_RECURSION_36(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_38(what, arg, x, ...) what(x, 37, arg) FOR_EACH_UNDER_RECURSION_37(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_39(what, arg, x, ...) what(x, 38, arg) FOR_EACH_UNDER_RECURSION_38(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_40(what, arg, x, ...) what(x, 39, arg) FOR_EACH_UNDER_RECURSION_39(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_41(what, arg, x, ...) what(x, 40, arg) FOR_EACH_UNDER_RECURSION_40(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_42(what, arg, x, ...) what(x, 41, arg) FOR_EACH_UNDER_RECURSION_41(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_43(what, arg, x, ...) what(x, 42, arg) FOR_EACH_UNDER_RECURSION_42(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_44(what, arg, x, ...) what(x, 43, arg) FOR_EACH_UNDER_RECURSION_43(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_45(what, arg, x, ...) what(x, 44, arg) FOR_EACH_UNDER_RECURSION_44(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_46(what, arg, x, ...) what(x, 45, arg) FOR_EACH_UNDER_RECURSION_45(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_47(what, arg, x, ...) what(x, 46, arg) FOR_EACH_UNDER_RECURSION_46(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_48(what, arg, x, ...) what(x, 47, arg) FOR_EACH_UNDER_RECURSION_47(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_49(what, arg, x, ...) what(x, 48, arg) FOR_EACH_UNDER_RECURSION_48(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_50(what, arg, x, ...) what(x, 49, arg) FOR_EACH_UNDER_RECURSION_49(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_51(what, arg, x, ...) what(x, 50, arg) FOR_EACH_UNDER_RECURSION_50(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_52(what, arg, x, ...) what(x, 51, arg) FOR_EACH_UNDER_RECURSION_51(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_53(what, arg, x, ...) what(x, 52, arg) FOR_EACH_UNDER_RECURSION_52(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_54(what, arg, x, ...) what(x, 53, arg) FOR_EACH_UNDER_RECURSION_53(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_55(what, arg, x, ...) what(x, 54, arg) FOR_EACH_UNDER_RECURSION_54(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_56(what, arg, x, ...) what(x, 55, arg) FOR_EACH_UNDER_RECURSION_55(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_57(what, arg, x, ...) what(x, 56, arg) FOR_EACH_UNDER_RECURSION_56(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_58(what, arg, x, ...) what(x, 57, arg) FOR_EACH_UNDER_RECURSION_57(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_59(what, arg, x, ...) what(x, 58, arg) FOR_EACH_UNDER_RECURSION_58(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_60(what, arg, x, ...) what(x, 59, arg) FOR_EACH_UNDER_RECURSION_59(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_61(what, arg, x, ...) what(x, 60, arg) FOR_EACH_UNDER_RECURSION_60(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_62(what, arg, x, ...) what(x, 61, arg) FOR_EACH_UNDER_RECURSION_61(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_63(what, arg, x, ...) what(x, 62, arg) FOR_EACH_UNDER_RECURSION_62(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_64(what, arg, x, ...) what(x, 63, arg) FOR_EACH_UNDER_RECURSION_63(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_65(what, arg, x, ...) what(x, 64, arg) FOR_EACH_UNDER_RECURSION_64(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_66(what, arg, x, ...) what(x, 65, arg) FOR_EACH_UNDER_RECURSION_65(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_67(what, arg, x, ...) what(x, 66, arg) FOR_EACH_UNDER_RECURSION_66(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_68(what, arg, x, ...) what(x, 67, arg) FOR_EACH_UNDER_RECURSION_67(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_69(what, arg, x, ...) what(x, 68, arg) FOR_EACH_UNDER_RECURSION_68(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_70(what, arg, x, ...) what(x, 69, arg) FOR_EACH_UNDER_RECURSION_69(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_71(what, arg, x, ...) what(x, 70, arg) FOR_EACH_UNDER_RECURSION_70(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_72(what, arg, x, ...) what(x, 71, arg) FOR_EACH_UNDER_RECURSION_71(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_73(what, arg, x, ...) what(x, 72, arg) FOR_EACH_UNDER_RECURSION_72(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_74(what, arg, x, ...) what(x, 73, arg) FOR_EACH_UNDER_RECURSION_73(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_75(what, arg, x, ...) what(x, 74, arg) FOR_EACH_UNDER_RECURSION_74(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_76(what, arg, x, ...) what(x, 75, arg) FOR_EACH_UNDER_RECURSION_75(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_77(what, arg, x, ...) what(x, 76, arg) FOR_EACH_UNDER_RECURSION_76(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_78(what, arg, x, ...) what(x, 77, arg) FOR_EACH_UNDER_RECURSION_77(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_79(what, arg, x, ...) what(x, 78, arg) FOR_EACH_UNDER_RECURSION_78(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_80(what, arg, x, ...) what(x, 79, arg) FOR_EACH_UNDER_RECURSION_79(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_81(what, arg, x, ...) what(x, 80, arg) FOR_EACH_UNDER_RECURSION_80(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_82(what, arg, x, ...) what(x, 81, arg) FOR_EACH_UNDER_RECURSION_81(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_83(what, arg, x, ...) what(x, 82, arg) FOR_EACH_UNDER_RECURSION_82(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_84(what, arg, x, ...) what(x, 83, arg) FOR_EACH_UNDER_RECURSION_83(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_85(what, arg, x, ...) what(x, 84, arg) FOR_EACH_UNDER_RECURSION_84(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_86(what, arg, x, ...) what(x, 85, arg) FOR_EACH_UNDER_RECURSION_85(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_87(what, arg, x, ...) what(x, 86, arg) FOR_EACH_UNDER_RECURSION_86(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_88(what, arg, x, ...) what(x, 87, arg) FOR_EACH_UNDER_RECURSION_87(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_89(what, arg, x, ...) what(x, 88, arg) FOR_EACH_UNDER_RECURSION_88(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_90(what, arg, x, ...) what(x, 89, arg) FOR_EACH_UNDER_RECURSION_89(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_91(what, arg, x, ...) what(x, 90, arg) FOR_EACH_UNDER_RECURSION_90(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_92(what, arg, x, ...) what(x, 91, arg) FOR_EACH_UNDER_RECURSION_91(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_93(what, arg, x, ...) what(x, 92, arg) FOR_EACH_UNDER_RECURSION_92(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_94(what, arg, x, ...) what(x, 93, arg) FOR_EACH_UNDER_RECURSION_93(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_95(what, arg, x, ...) what(x, 94, arg) FOR_EACH_UNDER_RECURSION_94(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_96(what, arg, x, ...) what(x, 95, arg) FOR_EACH_UNDER_RECURSION_95(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_97(what, arg, x, ...) what(x, 96, arg) FOR_EACH_UNDER_RECURSION_96(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_98(what, arg, x, ...) what(x, 97, arg) FOR_EACH_UNDER_RECURSION_97(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_99(what, arg, x, ...) what(x, 98, arg) FOR_EACH_UNDER_RECURSION_98(what, arg, ## __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION_100(what, arg, x, ...) what(x, 99, arg) FOR_EACH_UNDER_RECURSION_99(what, arg, ## __VA_ARGS__)

#define ARGS_COUNT(...) FOR_EACH_NARG_(__VA_ARGS__, FOR_EACH_RSEQ_N())
#define FOR_EACH_NARG_(...) FOR_EACH_ARG_N(__VA_ARGS__)

#define FOR_EACH_ARG_N(						\
	_1, _2, _3, _4, _5, _6, _7, _8, _9, _10,		\
	_11, _12, _13, _14, _15, _16, _17, _18, _19, _20,	\
	_21, _22, _23, _24, _25, _26, _27, _28, _29, _30,	\
	_31, _32, _33, _34, _35, _36, _37, _38, _39, _40,	\
	_41, _42, _43, _44, _45, _46, _47, _48, _49, _50,	\
	_51, _52, _53, _54, _55, _56, _57, _58, _59, _60,	\
	_61, _62, _63, _64, _65, _66, _67, _68, _69, _70,	\
	_71, _72, _73, _74, _75, _76, _77, _78, _79, _80,	\
	_81, _82, _83, _84, _85, _86, _87, _88, _89, _90,	\
	_91, _92, _93, _94, _95, _96, _97, _98, _99, _100,	\
	N, ...) N

#define FOR_EACH_RSEQ_N()				\
	100,						\
	99, 98, 97, 96, 95, 94, 93, 92, 91, 90,		\
	89, 88, 87, 86, 85, 84, 83, 82, 81, 80,		\
	79, 78, 77, 76, 75, 74, 73, 72, 71, 70,		\
	69, 68, 67, 66, 65, 64, 63, 62, 61, 60,		\
	59, 58, 57, 56, 55, 54, 53, 52, 51, 50,		\
	49, 48, 47, 46, 45, 44, 43, 42, 41, 40,		\
	39, 38, 37, 36, 35, 34, 33, 32, 31, 30,		\
	29, 28, 27, 26, 25, 24, 23, 22, 21, 20,		\
	19, 18, 17, 16, 15, 14, 13, 12, 11, 10,		\
	9, 8, 7, 6, 5, 4, 3, 2, 1, 0

#define FOR_EACH_(N, what, arg, ...) CONCATENATE(FOR_EACH_, N)(what, arg, __VA_ARGS__)
#define FOR_EACH(what, arg, ...) FOR_EACH_(ARGS_COUNT(__VA_ARGS__), what, arg, __VA_ARGS__)

#define FOR_EACH_UNDER_RECURSION_(N, what, arg, ...) CONCATENATE(FOR_EACH_UNDER_RECURSION_, N)(what, arg, __VA_ARGS__)
#define FOR_EACH_UNDER_RECURSION(what, arg, ...) FOR_EACH_UNDER_RECURSION_(ARGS_COUNT(__VA_ARGS__), what, arg, __VA_ARGS__)

#endif // __TUPLE_SPACE_HELPERS__
